### ISSUE TITLE
The nuget feed is broke/missing/never?

### ISSUE THREAD

**Issue by cottsak** [Readify/Owin.ForceHttps#1]
https://www.nuget.org/packages?q=ForcedHttps returns nothing.

Does `Install-Package Owin.ForcedHttps` actually work?

**Comment by robdmoore** [comment]
http://www.nuget.org/packages/Owin.ForceHttps

Drop the d ;)

**Comment by aaronpowell** [comment]
There's no D https://www.nuget.org/packages?q=ForceHttps

Sent from my Windows Phone
________________________________

**Comment by aaronpowell** [comment]
Fixed readme too

Sent from my Windows Phone
________________________________

**Comment by cottsak** [comment]
thanks guys
