### ISSUE TITLE
Support SSL offloading?

### ISSUE THREAD

**Issue by cottsak** [Readify/Owin.ForceHttps#4]
Hey is there a way to support SSL offloading like I'm doing here? https://github.com/cottsak/DevCookie/commit/63608dabd3ec58c71f420fc95820e93bf529af16#diff-b53e9cdf21d985b1a6362ce6b2fe3e5fR28

**Comment by aaronpowell** [comment]
Do you need to? If the request comes in as `HTTP` the middleware will force it to `HTTPS`, don't know why you'd need to look at the header too.

**Comment by cottsak** [comment]
If the SSL is offloaded at the load balancer and you then at the box try to redirect to HTTPS when the cert is not configured on said box, it will fail right?

**Comment by aaronpowell** [comment]
No idea. Isn't it the clients responsibility to do the certificate validation though?

**Comment by cottsak** [comment]
This is what I'm talking about https://github.com/cottsak/DevCookie/blob/master/DevCookie.Web/App_Start/RedirectToHttpsHelper.cs#L41

**Comment by aaronpowell** [comment]
Yeah I see what the code is doing but I don't get _when_ this would be applied. This middleware won't have any impact in a LB situation, the incoming request is checked for HTTPS and if not redirected to it, regardless of the header.

Or as you saying have an option to **only** apply the SSL redirect if the header is present?

**Comment by cottsak** [comment]
In many environments the SSL is stripped at the load balancer. I'm just trying to suggest we should make this package compatible with this scenario. In the code example I supplied, it is compatible and optional in that if you don't want to, you don't even need to turn it on. 

For example, AppHarbor does SSL Offloading so it's 100% necessary there.

In an SSL Offloading LB scenario, if you don't use the header to answer the question "are we secure?" then you get stuck in a redirect loop.

**Comment by aaronpowell** [comment]
I'm more than happy to see a PR for this, because as I've said I don't really get how this would fit in, but that could be more due to not having worked with forcing HTTS in a SSL offloading scenario.

**Comment by cottsak** [comment]
No sweat mate.

I don't have the F# knowledge for said PR yet and nor the time to learn right now (tho I want to). I'm going to stick with https://github.com/cottsak/DevCookie/blob/master/DevCookie.Web/App_Start/RedirectToHttpsHelper.cs for now.
